
FreeBSD: { enabled: no }
FreeBSD-kmods: { enabled: no }

FreeBSD-ports: {
  url: "http://suse-updates.int.firstyear.id.au/freebsd/${ABI}/quarterly",
  mirror_type: "none",
  signature_type: "fingerprints",
  fingerprints: "/usr/share/keys/pkg",
  enabled: yes
}
FreeBSD-ports-kmods: {
  url: "http://suse-updates.int.firstyear.id.au/freebsd/${ABI}/kmods_quarterly_${VERSION_MINOR}",
  mirror_type: "none",
  signature_type: "fingerprints",
  fingerprints: "/usr/share/keys/pkg",
  enabled: yes
}
FreeBSD-base: {
  url: "http://suse-updates.int.firstyear.id.au/freebsd/${ABI}/base_release_${VERSION_MINOR}",
  mirror_type: "none",
  signature_type: "fingerprints",
  # fingerprints: "/usr/share/keys/pkgbase-${VERSION_MAJOR}",
  fingerprints: "/usr/share/keys/pkg",
  enabled: yes
}
