[package]
name = "arc-disk-cache"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
concread = "^0.3"
tempfile = "3.2"
time = { version = "0.3", features = ["serde"]}
tracing = "0.1"
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
crc32c = "0.6"
base64 = "0.13.0"

[dev-dependencies]
tracing = { version = "0.1", features = ["attributes"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

